version: "3.8"

services:
  app:
    build:
      context: ./pipeline-practice   # 👈 tells Docker to look inside pipeline-practice folder
      dockerfile: Dockerfile         # 👈 explicitly use that Dockerfile
    container_name: python_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
